### PR TITLE
add mini two-digit nixie tubes, data format change, bump version number

### PR DESCRIPTION
**Pull request by sparr**
I love your mod and want to use it in a lot of small spaces around my factory. To that end, here's a patch that brings in a second kind of nixie tube, 1 tile instead of 2, with two small digits on it. I re-used your artwork, mostly just scaled down. I modified the nixie-map so that a nixie description can contain an arbitrary (equal) number of states and entities. I also added a migration script for the new recipe and data migration check  to handle the data format change.

### CODE REVIEW

**Comment by sparr** [comment]
Here's a screenshot:

screenshot of nixie tubes

(small and large nixies do not slave to each other)

**Comment by GopherAtl** [comment]
Nice, merging. Did this by chance also fix issue #6 that you reported a couple of days earlier?

**Comment by sparr** [comment]
I am not sure what happened with #6. A few save/reload later I found myself able to remove the nixie tubes, and I applied entity.destroy() to the leftover vehicle entities from when the bug was happening.

**Comment by GopherAtl** [comment]
hrm. Never ran into anything like that myself except during development, where it was a direct result of changes to the code between saving and loading, but I've not played any factorio in quite a while at this point. Lemme know if it crops up again.

**Pull request merged**
